# k8s/backend/analysis-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-service
  namespace: jse-stock-platform
  labels:
    app: analysis-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analysis-service
  template:
    metadata:
      labels:
        app: analysis-service
    spec:
      containers:
      - name: analysis-service
        image: jse-stock-platform/analysis-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: DYNAMODB_TABLE
          value: "jse_stock_data"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "700m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service
  namespace: jse-stock-platform
spec:
  selector:
    app: analysis-service
  ports:
  - port: 80
    targetPort: 8002
  type: ClusterIP