name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r services/auth-service/requirements.txt
        pip install -r services/scraper-service/requirements.txt
        pip install -r services/analysis-service/requirements.txt
        pip install -r services/notification-service/requirements.txt
        
    - name: Run tests
      run: |
        pytest services/auth-service/tests/
        pytest services/scraper-service/tests/
        pytest services/analysis-service/tests/
        pytest services/notification-service/tests/
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Auth Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/auth-service
        push: true
        tags: ghcr.io/${{ github.repository }}/auth-service:latest
        
    - name: Build and push Scraper Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/scraper-service
        push: true
        tags: ghcr.io/${{ github.repository }}/scraper-service:latest
        
    - name: Build and push Analysis Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/analysis-service
        push: true
        tags: ghcr.io/${{ github.repository }}/analysis-service:latest
        
    - name: Build and push Notification Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/notification-service
        push: true
        tags: ghcr.io/${{ github.repository }}/notification-service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name jse-stock-platform-cluster --region ${{ secrets.AWS_REGION }}
        
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/backend/auth-service.yaml
        kubectl apply -f k8s/backend/scraper-service.yaml
        kubectl apply -f k8s/backend/analysis-service.yaml
        kubectl apply -f k8s/backend/notification-service.yaml
        kubectl apply -f k8s/frontend/webapp.yaml
        kubectl apply -f k8s/ingress.yaml