# deploy.yml
name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Update Lambda Functions
        run: |
          for service in auth scraper analysis notification; do
            aws lambda update-function-code \
              --function-name jse-stock-platform-${service} \
              --image-uri ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/jse-stock-platform/${service}-service:${GITHUB_REF#refs/tags/}
          done
          
      - name: Update ECS Services
        run: |
          aws ecs update-service --cluster jse-stock-platform --service webapp \
            --force-new-deployment
            
      - name: Run Database Migrations
        run: |
          aws ecs run-task --cluster jse-stock-platform \
            --task-definition migrations \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[${SUBNET_IDS}],securityGroups=[${SECURITY_GROUP_IDS}]}"